service: medcloudserverlessfunctions

custom:
  settings:
    BUCKET: medcloudsannexes

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: us-east-1
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "arn:aws:s3:::*"

functions:
  optimize:
    handler: handler.optimize
    environment: 
      bucket: medcloudsannexes
    events:
      - s3:
          bucket: medcloudsannexes
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
      - s3:
          bucket: medcloudsannexes
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpeg
      - s3:
          bucket: medcloudsannexes
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
